[pytest]
base_url = https://www.saucedemo.com/
pythonpath = .

markers =
    API: all API only tests
    UI_all: all UI only tests
    UI_login: all login-related UI tests
    UI_other: other UI tests
    Pixel_perf: tests for comparing pages with snapshots
    to_develop: tests that needs to be refactored or fixed

addopts =
    --browser chromium
    --browser firefox

    -n 4

    --alluredir=allure-results
    --tracing retain-on-failure

    ##to uncomment if tests doesn't work
    --base-url https://www.saucedemo.com/